update m_sales_item set unit = '2', unit_price = unit_price/1000 WHERE item_id = '041B';
update m_sales_item set unit = '2', unit_price = unit_price/1000 WHERE item_id = '041C';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '1001';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '1002';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '1005';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '1006';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '1007';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '1008';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '144';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '145';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '146';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '157A';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '157B';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '157C';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '157E';
update m_sales_item set unit = '2', unit_price = unit_price/500 WHERE item_id = '160';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '162';
update m_sales_item set unit = '1', unit_price = unit_price*10 WHERE item_id = '1700';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '2002';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '2005';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '2006';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '204H';
update m_sales_item set unit = '1', unit_price = unit_price*10 WHERE item_id = '26D1';
update m_sales_item set unit = '1', unit_price = unit_price*10 WHERE item_id = '26D2';
update m_sales_item set unit = '1', unit_price = unit_price*10 WHERE item_id = '26D3';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '508Y';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '518DR';
update m_sales_item set unit = '1', unit_price = unit_price*30 WHERE item_id = '518HC';
update m_sales_item set unit = '1', unit_price = unit_price*30 WHERE item_id = '518HL';
update m_sales_item set unit = '1', unit_price = unit_price*30 WHERE item_id = '518HP';
update m_sales_item set unit = '1', unit_price = unit_price*30 WHERE item_id = '518HR';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '518K';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '518K1';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '518M';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '518S';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '518S1';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '518WG';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '518Y';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '518Z';
update m_sales_item set unit = '1', unit_price = unit_price*10 WHERE item_id = '526H';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '526Y';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '528M';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '528WG';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '528Y';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '528Z';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = '529';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = '530';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = '531';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = '532';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = '533';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = '534';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '538DR';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '538M';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '538Y';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '548M';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = '548Y';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = '550';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = '551';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = '552';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '70BA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '70FA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '70GA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '70K';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '70M';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = '70R';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = 'A210';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = 'A218';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'A3W10';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'A3W7';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'A3W76';
update m_sales_item set unit = '1', unit_price = unit_price*50 WHERE item_id = 'A508R';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AFBA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AFFA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AFGA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AFMA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AFPA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AFRA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AFRB';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AFSA';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AW10';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AW5';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AW7';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AW76';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'AW8';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'L11';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'L12';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'L13';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'L4';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'L5';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'L6';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'L7';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'L8';
update m_sales_item set unit = '2', unit_price = unit_price/500 WHERE item_id = 'N1600';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = 'T101';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = 'T102';
update m_sales_item set unit = '2', unit_price = unit_price/100 WHERE item_id = 'T103';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'T145';
update m_sales_item set unit = '1', unit_price = unit_price*100 WHERE item_id = 'T9';


UPDATE t_stock_infomation SET stock_count=stock_count*1000, assumption_stock_count=assumption_stock_count*1000 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='041B');
UPDATE t_stock_infomation SET stock_count=stock_count*1000, assumption_stock_count=assumption_stock_count*1000 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='041C');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='1001');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='1002');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='1005');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='1006');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='1007');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='1008');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='144');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='145');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='146');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='157A');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='157B');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='157C');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='157E');
UPDATE t_stock_infomation SET stock_count=stock_count*500, assumption_stock_count=assumption_stock_count*500 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='160');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='162');
UPDATE t_stock_infomation SET stock_count=stock_count/10, assumption_stock_count=assumption_stock_count/10 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='1700');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='2002');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='2005');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='2006');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='204H');
UPDATE t_stock_infomation SET stock_count=stock_count/10, assumption_stock_count=assumption_stock_count/10 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='26D1');
UPDATE t_stock_infomation SET stock_count=stock_count/10, assumption_stock_count=assumption_stock_count/10 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='26D2');
UPDATE t_stock_infomation SET stock_count=stock_count/10, assumption_stock_count=assumption_stock_count/10 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='26D3');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='508Y');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518DR');
UPDATE t_stock_infomation SET stock_count=stock_count/30, assumption_stock_count=assumption_stock_count/30 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518HC');
UPDATE t_stock_infomation SET stock_count=stock_count/30, assumption_stock_count=assumption_stock_count/30 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518HL');
UPDATE t_stock_infomation SET stock_count=stock_count/30, assumption_stock_count=assumption_stock_count/30 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518HP');
UPDATE t_stock_infomation SET stock_count=stock_count/30, assumption_stock_count=assumption_stock_count/30 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518HR');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518K');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518K1');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518M');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518S');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518S1');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518WG');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518Y');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='518Z');
UPDATE t_stock_infomation SET stock_count=stock_count/10, assumption_stock_count=assumption_stock_count/10 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='526H');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='526Y');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='528M');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='528WG');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='528Y');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='528Z');
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='529');
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='530');
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='531');
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='532');
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='533');
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='534');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='538DR');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='538M');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='538Y');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='548M');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='548Y');
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = 513;
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id =515;
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id =517;
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='70BA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='70FA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='70GA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='70K');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='70M');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='70R');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='A210');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='A218');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='A3W10');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='A3W7');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='A3W76');
UPDATE t_stock_infomation SET stock_count=stock_count/50, assumption_stock_count=assumption_stock_count/50 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='A508R');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AFBA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AFFA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AFGA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AFMA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AFPA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AFRA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AFRB');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AFSA');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AW10');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AW5');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AW7');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AW76');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='AW8');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='L11');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='L12');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='L13');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='L4');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='L5');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='L6');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='L7');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='L8');
UPDATE t_stock_infomation SET stock_count=stock_count*500, assumption_stock_count=assumption_stock_count*500 WHERE item_id = 779;
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='T101');
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='T102');
UPDATE t_stock_infomation SET stock_count=stock_count*100, assumption_stock_count=assumption_stock_count*100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='T103');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='T145');
UPDATE t_stock_infomation SET stock_count=stock_count/100, assumption_stock_count=assumption_stock_count/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='T9');



update t_orders_item set item_quantity=item_quantity*1000, unit_price = unit_price/1000 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='041B');
update t_orders_item set item_quantity=item_quantity*1000, unit_price = unit_price/1000 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='041C');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='1001');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='1002');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='1005');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='1006');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='1007');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='1008');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='144');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='145');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='146');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='157A');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='157B');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='157C');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='157E');
update t_orders_item set item_quantity=item_quantity*500, unit_price = unit_price/500 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='160');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='162');
update t_orders_item set item_quantity=item_quantity/10, unit_price = unit_price*10 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='1700');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='2002');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='2005');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='2006');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='204H');
update t_orders_item set item_quantity=item_quantity/10, unit_price = unit_price*10 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='26D1');
update t_orders_item set item_quantity=item_quantity/10, unit_price = unit_price*10 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='26D2');
update t_orders_item set item_quantity=item_quantity/10, unit_price = unit_price*10 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='26D3');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='508Y');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518DR');
update t_orders_item set item_quantity=item_quantity/30, unit_price = unit_price*30 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518HC');
update t_orders_item set item_quantity=item_quantity/30, unit_price = unit_price*30 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518HL');
update t_orders_item set item_quantity=item_quantity/30, unit_price = unit_price*30 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518HP');
update t_orders_item set item_quantity=item_quantity/30, unit_price = unit_price*30 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518HR');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518K');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518K1');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518M');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518S');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518S1');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518WG');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518Y');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='518Z');
update t_orders_item set item_quantity=item_quantity/10, unit_price = unit_price*10 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='526H');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='526Y');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='528M');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='528WG');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='528Y');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='528Z');
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='529');
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='530');
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='531');
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='532');
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='533');
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='534');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='538DR');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='538M');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='538Y');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='548M');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='548Y');
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id =513;
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = 515;
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id =517;
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='70BA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='70FA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='70GA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='70K');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='70M');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='70R');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='A210');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='A218');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='A3W10');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='A3W7');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='A3W76');
update t_orders_item set item_quantity=item_quantity/50, unit_price = unit_price*50 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='A508R');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AFBA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AFFA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AFGA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AFMA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AFPA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AFRA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AFRB');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AFSA');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AW10');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AW5');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AW7');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AW76');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='AW8');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='L11');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='L12');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='L13');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='L4');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='L5');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='L6');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='L7');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='L8');
update t_orders_item set item_quantity=item_quantity*500, unit_price = unit_price/500 WHERE item_id =779;
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='T101');
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='T102');
update t_orders_item set item_quantity=item_quantity*100, unit_price = unit_price/100 WHERE item_id = (select system_item_id from m_sales_item WHERE item_id='T103');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='T145');
update t_orders_item set item_quantity=item_quantity/100, unit_price = unit_price*100 WHERE item_id =  (select system_item_id from m_sales_item WHERE item_id='T9');
