-- 顧客

DROP TABLE M_CUSTOMER_DATA;

CREATE TABLE M_CUSTOMER_DATA
(
	CUSTOMER_ID		serial	NOT NULL,
	OLD_CUSTOMER_ID		char(10),
	CUSTOMER_TYPE		char(1),
	OFFICE_NAME		text[],
	TITLE		varchar(30)[],
	NAME_KANA		text[],
	NAME_KANJI		text[],
	TEL_NO		varchar(13)[],
	FAX_NO		varchar(13)[],
	EMAIL		varchar(256)[],
	ZIP		varchar(30)[],
	PREFECTURES_ID		varchar(2)[],
	MUNICIPALITY		text[],
	ADDRESS		text[],
	BUS_PLACE_ID		char(1),
	BUS_USER_ID		int4,
	REMARKS		text,
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT M_CUSTOMER_DATA_pkey PRIMARY KEY (CUSTOMER_ID));


COMMENT ON TABLE M_CUSTOMER_DATA IS '顧客';
COMMENT ON COLUMN M_CUSTOMER_DATA.CUSTOMER_ID IS '顧客ID';
COMMENT ON COLUMN M_CUSTOMER_DATA.OLD_CUSTOMER_ID IS '旧顧客ID';
COMMENT ON COLUMN M_CUSTOMER_DATA.CUSTOMER_TYPE IS '顧客区分';
COMMENT ON COLUMN M_CUSTOMER_DATA.OFFICE_NAME IS '事務所名';
COMMENT ON COLUMN M_CUSTOMER_DATA.TITLE IS '肩書き';
COMMENT ON COLUMN M_CUSTOMER_DATA.NAME_KANA IS '名前(かな)';
COMMENT ON COLUMN M_CUSTOMER_DATA.NAME_KANJI IS '名前(漢字)';
COMMENT ON COLUMN M_CUSTOMER_DATA.TEL_NO IS '電話番号';
COMMENT ON COLUMN M_CUSTOMER_DATA.FAX_NO IS 'FAX';
COMMENT ON COLUMN M_CUSTOMER_DATA.EMAIL IS 'E-Mail';
COMMENT ON COLUMN M_CUSTOMER_DATA.ZIP IS '郵便番号';
COMMENT ON COLUMN M_CUSTOMER_DATA.PREFECTURES_ID IS '都道府県';
COMMENT ON COLUMN M_CUSTOMER_DATA.MUNICIPALITY IS '市区町村';
COMMENT ON COLUMN M_CUSTOMER_DATA.ADDRESS IS '町域番地';
COMMENT ON COLUMN M_CUSTOMER_DATA.BUS_PLACE_ID IS '担当営業所';
COMMENT ON COLUMN M_CUSTOMER_DATA.BUS_USER_ID IS '担当営業';
COMMENT ON COLUMN M_CUSTOMER_DATA.REMARKS IS '備考';
COMMENT ON COLUMN M_CUSTOMER_DATA.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN M_CUSTOMER_DATA.CREATE_DATE IS '登録日';
COMMENT ON COLUMN M_CUSTOMER_DATA.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN M_CUSTOMER_DATA.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN M_CUSTOMER_DATA.UPDATE_USER_ID IS '更新者ID';

