-- 発注先

DROP TABLE M_ORDER_DESTINATION;

CREATE TABLE M_ORDER_DESTINATION
(
	SYSTEM_ORDER_DESTINATION_ID		serial	NOT NULL,
	ORDER_DESTINATION_CODE		int4	NOT NULL,
	ORDER_DESTINATION_NM		varchar(50),
	TEL_NO		varchar(13),
	FAX_NO		varchar(13),
	MAIL_ADDRESS		varchar(256),
	ZIP		varchar(8),
	PREFECTURES		varchar(2),
	MUNICIPALITY		text,
	ADDRESS		text,
	REMARKS		text,
	ENABLED_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT M_ORDER_DESTINATION_pkey PRIMARY KEY (SYSTEM_ORDER_DESTINATION_ID));


COMMENT ON TABLE M_ORDER_DESTINATION IS '発注先';
COMMENT ON COLUMN M_ORDER_DESTINATION.SYSTEM_ORDER_DESTINATION_ID IS 'システム発注先ID';
COMMENT ON COLUMN M_ORDER_DESTINATION.ORDER_DESTINATION_CODE IS '発注先コード';
COMMENT ON COLUMN M_ORDER_DESTINATION.ORDER_DESTINATION_NM IS '発注先名';
COMMENT ON COLUMN M_ORDER_DESTINATION.TEL_NO IS '電話番号';
COMMENT ON COLUMN M_ORDER_DESTINATION.FAX_NO IS 'FAX';
COMMENT ON COLUMN M_ORDER_DESTINATION.MAIL_ADDRESS IS 'E-Mail';
COMMENT ON COLUMN M_ORDER_DESTINATION.ZIP IS '郵便番号';
COMMENT ON COLUMN M_ORDER_DESTINATION.PREFECTURES IS '都道府県';
COMMENT ON COLUMN M_ORDER_DESTINATION.MUNICIPALITY IS '市区町村';
COMMENT ON COLUMN M_ORDER_DESTINATION.ADDRESS IS '町域番地';
COMMENT ON COLUMN M_ORDER_DESTINATION.REMARKS IS '備考';
COMMENT ON COLUMN M_ORDER_DESTINATION.ENABLED_FLAG IS '有効無効フラグ';
COMMENT ON COLUMN M_ORDER_DESTINATION.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN M_ORDER_DESTINATION.CREATE_DATE IS '登録日';
COMMENT ON COLUMN M_ORDER_DESTINATION.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN M_ORDER_DESTINATION.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN M_ORDER_DESTINATION.UPDATE_USER_ID IS '更新者ID';

