-- ユーザー

DROP TABLE M_USER_AREA;

CREATE TABLE M_USER_AREA
(
	SYS_AREA_ID		serial	NOT NULL,
	USER_ID		varchar(20)	NOT NULL,
	PREFECTURES		varchar(2),
	MUNICIPALITY		text,
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT M_USER_AREA_pkey PRIMARY KEY (SYS_AREA_ID));


COMMENT ON TABLE M_USER_AREA IS 'ユーザー';
COMMENT ON COLUMN M_USER_AREA.SYS_AREA_ID IS 'システムエリアID';
COMMENT ON COLUMN M_USER_AREA.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN M_USER_AREA.PREFECTURES IS '都道府県';
COMMENT ON COLUMN M_USER_AREA.MUNICIPALITY IS '市区町村';
COMMENT ON COLUMN M_USER_AREA.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN M_USER_AREA.CREATE_DATE IS '登録日';
COMMENT ON COLUMN M_USER_AREA.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN M_USER_AREA.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN M_USER_AREA.UPDATE_USER_ID IS '更新者ID';

