-- ユーザー

DROP TABLE M_USER_DATA;

CREATE TABLE M_USER_DATA
(
	SYS_USER_ID		serial	NOT NULL,
	LOGIN_CD		varchar(20)	NOT NULL,
	PASSWORD		varchar(64)	NOT NULL,
	USER_NAME		varchar(30),
	DEPARTMENT		char(1)	NOT NULL,
	SALES_OFFICE		char(1)	NOT NULL,
	REMARKS		text,
	USE_FLAG		char(1)	NOT NULL,
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT M_USER_DATA_pkey PRIMARY KEY (SYS_USER_ID));


COMMENT ON TABLE M_USER_DATA IS 'ユーザー';
COMMENT ON COLUMN M_USER_DATA.SYS_USER_ID IS 'システムユーザーID';
COMMENT ON COLUMN M_USER_DATA.LOGIN_CD IS 'ログインコード';
COMMENT ON COLUMN M_USER_DATA.PASSWORD IS 'パスワード';
COMMENT ON COLUMN M_USER_DATA.USER_NAME IS 'ユーザ名';
COMMENT ON COLUMN M_USER_DATA.DEPARTMENT IS '部署';
COMMENT ON COLUMN M_USER_DATA.SALES_OFFICE IS '営業所';
COMMENT ON COLUMN M_USER_DATA.REMARKS IS '備考';
COMMENT ON COLUMN M_USER_DATA.USE_FLAG IS '使用フラグ';
COMMENT ON COLUMN M_USER_DATA.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN M_USER_DATA.CREATE_DATE IS '登録日';
COMMENT ON COLUMN M_USER_DATA.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN M_USER_DATA.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN M_USER_DATA.UPDATE_USER_ID IS '更新者ID';

