-- 送付情報

DROP TABLE T_DELIVERY_DATA;

CREATE TABLE T_DELIVERY_DATA
(
	DELIVERY_ID		serial	NOT NULL,
	DELIVERY_DATE		timestamp,
	DELIVERY_ITEM		text,
	DELIVERY_DETAIL		text,
	CUSTOMER_ID		int4,
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_DELIVERY_DATA_pkey PRIMARY KEY (DELIVERY_ID));


COMMENT ON TABLE T_DELIVERY_DATA IS '送付情報';
COMMENT ON COLUMN T_DELIVERY_DATA.DELIVERY_ID IS '送付ID';
COMMENT ON COLUMN T_DELIVERY_DATA.DELIVERY_DATE IS '送付日付';
COMMENT ON COLUMN T_DELIVERY_DATA.DELIVERY_ITEM IS '送付物';
COMMENT ON COLUMN T_DELIVERY_DATA.DELIVERY_DETAIL IS '送付内容';
COMMENT ON COLUMN T_DELIVERY_DATA.CUSTOMER_ID IS '顧客ID';
COMMENT ON COLUMN T_DELIVERY_DATA.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN T_DELIVERY_DATA.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_DELIVERY_DATA.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_DELIVERY_DATA.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_DELIVERY_DATA.UPDATE_USER_ID IS '更新者ID';

