-- 見積

DROP TABLE T_ESTIMATES_DATA;

CREATE TABLE T_ESTIMATES_DATA
(
	SYSTEM_ESTIMATES_ID		serial	NOT NULL,
	OLD_ESTIMATES_ID		char(10),
	ISSUE_FLAG		char(1)	DEFAULT 'f'	NOT NULL,
	DISPATCH_FLAG		char(1)	DEFAULT 'f'	NOT NULL,
	FINISHED_FLAG		char(1)	DEFAULT 'f'	NOT NULL,
	ESTIMATE_CONFIRM		char(1)	DEFAULT 'f'	NOT NULL,
	ESTIMATES_DATE		timestamp,
	ESTIMATES_ROUTE		varchar(2),
	SLIP_ID		int4,
	SLIP_DATE		timestamp,
	DELIVERY_PLACE		text,
	EXPIRATION_DATE		timestamp,
	EXPECTED_SHIPPING_DATE		timestamp,
	ARRAIVAL_DATE		timestamp,
	DELIVERY_TIME_ZONE		char(1),
	ESTIMATES_OFFICE		char(1),
	ESTIMATES_USER_ID		int4,
	USER_ID		int4,
	PAYMENT_METHOD		char(1),
	INVOICE_TYPE		char(1),
	NAME		text,
	HONORIFIC		text,
	ZIP		varchar(8),
	ADDRESS1		text,
	ADDRESS2		text,
	TEL_NO		varchar(13),
	FAX_NO		varchar(13),
	EMAIL		varchar(256),
	SLIP_REMARKS		text,
	INTERNAL_REMARKS		text,
	CUSTOMER_ID		int4,
	SUB_TOTAL		int4,
	SALES_TAX		int4,
	GRAND_TOTAL		int4,
	OLD_ESTIMATES_ROUTE		varchar(2),
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_ESTIMATES_DATA_pkey PRIMARY KEY (SYSTEM_ESTIMATES_ID));


COMMENT ON TABLE T_ESTIMATES_DATA IS '見積';
COMMENT ON COLUMN T_ESTIMATES_DATA.SYSTEM_ESTIMATES_ID IS 'システム見積ID';
COMMENT ON COLUMN T_ESTIMATES_DATA.OLD_ESTIMATES_ID IS '旧見積ID';
COMMENT ON COLUMN T_ESTIMATES_DATA.ISSUE_FLAG IS 'ステータス：起伝';
COMMENT ON COLUMN T_ESTIMATES_DATA.DISPATCH_FLAG IS 'ステータス：発送';
COMMENT ON COLUMN T_ESTIMATES_DATA.FINISHED_FLAG IS 'ステータス：完成';
COMMENT ON COLUMN T_ESTIMATES_DATA.ESTIMATE_CONFIRM IS '注文確定フラグ';
COMMENT ON COLUMN T_ESTIMATES_DATA.ESTIMATES_DATE IS '見積日';
COMMENT ON COLUMN T_ESTIMATES_DATA.ESTIMATES_ROUTE IS '見積経路';
COMMENT ON COLUMN T_ESTIMATES_DATA.SLIP_ID IS '伝票No';
COMMENT ON COLUMN T_ESTIMATES_DATA.SLIP_DATE IS '伝票作成日';
COMMENT ON COLUMN T_ESTIMATES_DATA.DELIVERY_PLACE IS '納入場所';
COMMENT ON COLUMN T_ESTIMATES_DATA.EXPIRATION_DATE IS '有効期限';
COMMENT ON COLUMN T_ESTIMATES_DATA.EXPECTED_SHIPPING_DATE IS '出荷予定日';
COMMENT ON COLUMN T_ESTIMATES_DATA.ARRAIVAL_DATE IS '納期';
COMMENT ON COLUMN T_ESTIMATES_DATA.DELIVERY_TIME_ZONE IS '配達時間帯';
COMMENT ON COLUMN T_ESTIMATES_DATA.ESTIMATES_OFFICE IS '見積営業所';
COMMENT ON COLUMN T_ESTIMATES_DATA.ESTIMATES_USER_ID IS '見積担当';
COMMENT ON COLUMN T_ESTIMATES_DATA.USER_ID IS '担当者';
COMMENT ON COLUMN T_ESTIMATES_DATA.PAYMENT_METHOD IS '支払方法';
COMMENT ON COLUMN T_ESTIMATES_DATA.INVOICE_TYPE IS '送り状種別';
COMMENT ON COLUMN T_ESTIMATES_DATA.NAME IS '宛名';
COMMENT ON COLUMN T_ESTIMATES_DATA.HONORIFIC IS '敬称';
COMMENT ON COLUMN T_ESTIMATES_DATA.ZIP IS '郵便番号';
COMMENT ON COLUMN T_ESTIMATES_DATA.ADDRESS1 IS '住所1';
COMMENT ON COLUMN T_ESTIMATES_DATA.ADDRESS2 IS '住所2';
COMMENT ON COLUMN T_ESTIMATES_DATA.TEL_NO IS 'TEL';
COMMENT ON COLUMN T_ESTIMATES_DATA.FAX_NO IS 'FAX';
COMMENT ON COLUMN T_ESTIMATES_DATA.EMAIL IS 'E-mail';
COMMENT ON COLUMN T_ESTIMATES_DATA.SLIP_REMARKS IS '伝票備考';
COMMENT ON COLUMN T_ESTIMATES_DATA.INTERNAL_REMARKS IS '内部備考';
COMMENT ON COLUMN T_ESTIMATES_DATA.CUSTOMER_ID IS '顧客ID';
COMMENT ON COLUMN T_ESTIMATES_DATA.SUB_TOTAL IS '小計';
COMMENT ON COLUMN T_ESTIMATES_DATA.SALES_TAX IS '消費税';
COMMENT ON COLUMN T_ESTIMATES_DATA.GRAND_TOTAL IS '合計';
COMMENT ON COLUMN T_ESTIMATES_DATA.OLD_ESTIMATES_ROUTE IS '旧担当者';
COMMENT ON COLUMN T_ESTIMATES_DATA.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN T_ESTIMATES_DATA.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_ESTIMATES_DATA.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_ESTIMATES_DATA.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_ESTIMATES_DATA.UPDATE_USER_ID IS '更新者ID';

