-- 受注

DROP TABLE T_ORDERS_DATA;

CREATE TABLE T_ORDERS_DATA
(
	SYSTEM_ORDERS_ID		serial	NOT NULL,
	OLD_ORDERS_ID		char(10),
	ISSUE_FLAG		char(1)	DEFAULT 'f'	NOT NULL,
	DISPATCH_FLAG		char(1)	DEFAULT 'f'	NOT NULL,
	FINISHED_FLAG		char(1)	DEFAULT 'f'	NOT NULL,
	ORDER_CONFIRM		char(1)	DEFAULT 'f'	NOT NULL,
	ORDERS_DATE		timestamp,
	ORDERS_ROUTE		varchar(2),
	SLIP_ID		int4,
	SLIP_DATE		timestamp,
	EXPECTED_SHIPPING_DATE		timestamp,
	ARRAIVAL_DATE		timestamp,
	DELIVERY_TIME_ZONE		char(1),
	ORDERS_OFFICE		char(1),
	ORDERS_USER_ID		int4,
	USER_ID		int4,
	PAYMENT_METHOD		char(1),
	INVOICE_TYPE		char(1),
	NAME		text,
	HONORIFIC		text,
	ZIP		varchar(8),
	ADDRESS1		text,
	ADDRESS2		text,
	TEL_NO		varchar(13),
	FAX_NO		varchar(13),
	EMAIL		varchar(256),
	SLIP_REMARKS		text,
	INTERNAL_REMARKS		text,
	CUSTOMER_ID		int4,
	SUB_TOTAL		int4,
	SALES_TAX		int4,
	GRAND_TOTAL		int4,
	OLD_ORDERS_ROUTE		varchar(2),
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_ORDERS_DATA_pkey PRIMARY KEY (SYSTEM_ORDERS_ID));


COMMENT ON TABLE T_ORDERS_DATA IS '受注';
COMMENT ON COLUMN T_ORDERS_DATA.SYSTEM_ORDERS_ID IS 'システム受注ID';
COMMENT ON COLUMN T_ORDERS_DATA.OLD_ORDERS_ID IS '旧受注ID';
COMMENT ON COLUMN T_ORDERS_DATA.ISSUE_FLAG IS 'ステータス：起伝';
COMMENT ON COLUMN T_ORDERS_DATA.DISPATCH_FLAG IS 'ステータス：発送';
COMMENT ON COLUMN T_ORDERS_DATA.FINISHED_FLAG IS 'ステータス：完成';
COMMENT ON COLUMN T_ORDERS_DATA.ORDER_CONFIRM IS '注文確定フラグ';
COMMENT ON COLUMN T_ORDERS_DATA.ORDERS_DATE IS '受付日';
COMMENT ON COLUMN T_ORDERS_DATA.ORDERS_ROUTE IS '受注経路';
COMMENT ON COLUMN T_ORDERS_DATA.SLIP_ID IS '伝票No';
COMMENT ON COLUMN T_ORDERS_DATA.SLIP_DATE IS '伝票作成日';
COMMENT ON COLUMN T_ORDERS_DATA.EXPECTED_SHIPPING_DATE IS '出荷予定日';
COMMENT ON COLUMN T_ORDERS_DATA.ARRAIVAL_DATE IS '到着日';
COMMENT ON COLUMN T_ORDERS_DATA.DELIVERY_TIME_ZONE IS '配達時間帯';
COMMENT ON COLUMN T_ORDERS_DATA.ORDERS_OFFICE IS '受注営業所';
COMMENT ON COLUMN T_ORDERS_DATA.ORDERS_USER_ID IS '受注担当';
COMMENT ON COLUMN T_ORDERS_DATA.USER_ID IS '担当者';
COMMENT ON COLUMN T_ORDERS_DATA.PAYMENT_METHOD IS '支払方法';
COMMENT ON COLUMN T_ORDERS_DATA.INVOICE_TYPE IS '送り状種別';
COMMENT ON COLUMN T_ORDERS_DATA.NAME IS '宛名';
COMMENT ON COLUMN T_ORDERS_DATA.HONORIFIC IS '敬称';
COMMENT ON COLUMN T_ORDERS_DATA.ZIP IS '郵便番号';
COMMENT ON COLUMN T_ORDERS_DATA.ADDRESS1 IS '住所1';
COMMENT ON COLUMN T_ORDERS_DATA.ADDRESS2 IS '住所2';
COMMENT ON COLUMN T_ORDERS_DATA.TEL_NO IS 'TEL';
COMMENT ON COLUMN T_ORDERS_DATA.FAX_NO IS 'FAX';
COMMENT ON COLUMN T_ORDERS_DATA.EMAIL IS 'E-mail';
COMMENT ON COLUMN T_ORDERS_DATA.SLIP_REMARKS IS '伝票備考';
COMMENT ON COLUMN T_ORDERS_DATA.INTERNAL_REMARKS IS '内部備考';
COMMENT ON COLUMN T_ORDERS_DATA.CUSTOMER_ID IS '顧客ID';
COMMENT ON COLUMN T_ORDERS_DATA.SUB_TOTAL IS '小計';
COMMENT ON COLUMN T_ORDERS_DATA.SALES_TAX IS '消費税';
COMMENT ON COLUMN T_ORDERS_DATA.GRAND_TOTAL IS '合計';
COMMENT ON COLUMN T_ORDERS_DATA.OLD_ORDERS_ROUTE IS '旧担当者';
COMMENT ON COLUMN T_ORDERS_DATA.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN T_ORDERS_DATA.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_ORDERS_DATA.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_ORDERS_DATA.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_ORDERS_DATA.UPDATE_USER_ID IS '更新者ID';

