-- 受注送り状

DROP TABLE T_ORDERS_INVOICE;

CREATE TABLE T_ORDERS_INVOICE
(
	INVOICE_ID		serial	NOT NULL,
	ORDERS_ID		int4,
	INVOICE_ZIP		varchar(8),
	INVOICE_TEL_NO		varchar(13),
	INVOICE_ADDRESS		text,
	INVOICE_NAME		text,
	INVOICE_HONORIFIC		text,
	INVOICE_NUMBER		int4	DEFAULT '1',
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_ORDERS_INVOICE_pkey PRIMARY KEY (INVOICE_ID));


COMMENT ON TABLE T_ORDERS_INVOICE IS '受注送り状';
COMMENT ON COLUMN T_ORDERS_INVOICE.INVOICE_ID IS '受注送り状ID';
COMMENT ON COLUMN T_ORDERS_INVOICE.ORDERS_ID IS '受注No';
COMMENT ON COLUMN T_ORDERS_INVOICE.INVOICE_ZIP IS '送り状郵便番号';
COMMENT ON COLUMN T_ORDERS_INVOICE.INVOICE_TEL_NO IS '送り状電話番号';
COMMENT ON COLUMN T_ORDERS_INVOICE.INVOICE_ADDRESS IS '送り状住所';
COMMENT ON COLUMN T_ORDERS_INVOICE.INVOICE_NAME IS '送り状氏名';
COMMENT ON COLUMN T_ORDERS_INVOICE.INVOICE_HONORIFIC IS '送り状敬称';
COMMENT ON COLUMN T_ORDERS_INVOICE.INVOICE_NUMBER IS '個口数';
COMMENT ON COLUMN T_ORDERS_INVOICE.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN T_ORDERS_INVOICE.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_ORDERS_INVOICE.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_ORDERS_INVOICE.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_ORDERS_INVOICE.UPDATE_USER_ID IS '更新者ID';

