-- リピート告知

DROP TABLE T_REPEAT_ANNOUNCEMENT;

CREATE TABLE T_REPEAT_ANNOUNCEMENT
(
	REPEAT_ID		serial	NOT NULL,
	ANNOUNCEMENT_DATE		timestamp,
	ANNOUNCEMENT_DETAIL		text,
	CUSTOMER_ID		int4,
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_REPEAT_ANNOUNCEMENT_pkey PRIMARY KEY (REPEAT_ID));


COMMENT ON TABLE T_REPEAT_ANNOUNCEMENT IS 'リピート告知';
COMMENT ON COLUMN T_REPEAT_ANNOUNCEMENT.REPEAT_ID IS 'リピートID';
COMMENT ON COLUMN T_REPEAT_ANNOUNCEMENT.ANNOUNCEMENT_DATE IS '告知日付';
COMMENT ON COLUMN T_REPEAT_ANNOUNCEMENT.ANNOUNCEMENT_DETAIL IS '告知内容';
COMMENT ON COLUMN T_REPEAT_ANNOUNCEMENT.CUSTOMER_ID IS '顧客ID';
COMMENT ON COLUMN T_REPEAT_ANNOUNCEMENT.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN T_REPEAT_ANNOUNCEMENT.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_REPEAT_ANNOUNCEMENT.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_REPEAT_ANNOUNCEMENT.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_REPEAT_ANNOUNCEMENT.UPDATE_USER_ID IS '更新者ID';

