-- 商品メモ

DROP TABLE T_SALES_ITEM_MEMO;

CREATE TABLE T_SALES_ITEM_MEMO
(
	ITEM_MEMO_ID		serial	NOT NULL,
	STAFF		text,
	DETAIL		text,
	ITEM_ID		char(4),
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_SALES_ITEM_MEMO_pkey PRIMARY KEY (ITEM_MEMO_ID));


COMMENT ON TABLE T_SALES_ITEM_MEMO IS '商品メモ';
COMMENT ON COLUMN T_SALES_ITEM_MEMO.ITEM_MEMO_ID IS '商品ID';
COMMENT ON COLUMN T_SALES_ITEM_MEMO.STAFF IS '担当者';
COMMENT ON COLUMN T_SALES_ITEM_MEMO.DETAIL IS '内容';
COMMENT ON COLUMN T_SALES_ITEM_MEMO.ITEM_ID IS '商品ID';
COMMENT ON COLUMN T_SALES_ITEM_MEMO.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN T_SALES_ITEM_MEMO.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_SALES_ITEM_MEMO.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_SALES_ITEM_MEMO.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_SALES_ITEM_MEMO.UPDATE_USER_ID IS '更新者ID';

