-- 伝票用顧客情報

DROP TABLE T_SLIP_CUSTOMER_DATA;

CREATE TABLE T_SLIP_CUSTOMER_DATA
(
	SLIP_CUSTOMER_ID		serial	NOT NULL,
	CUSTOMER_ID		int4,
	NAME		text,
	HONORIFIC		text,
	ZIP		varchar(13),
	ADDRESS1		text,
	ADDRESS2		text,
	TEL_NO		varchar(13),
	FAX_NO		varchar(13),
	EMAIL		varchar(256),
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_SLIP_CUSTOMER_DATA_pkey PRIMARY KEY (SLIP_CUSTOMER_ID));


COMMENT ON TABLE T_SLIP_CUSTOMER_DATA IS '伝票用顧客情報';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.SLIP_CUSTOMER_ID IS '伝票用顧客情報ID';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.CUSTOMER_ID IS '顧客ID';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.NAME IS '名前';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.HONORIFIC IS '敬称';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.ZIP IS '郵便番号';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.ADDRESS1 IS '住所1';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.ADDRESS2 IS '住所2';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.TEL_NO IS '電話番号';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.FAX_NO IS 'FAX';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.EMAIL IS 'E-Mail';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_SLIP_CUSTOMER_DATA.UPDATE_USER_ID IS '更新者ID';

