-- 排他制御

DROP TABLE T_STOCK_EXCLUSIVE;

CREATE TABLE T_STOCK_EXCLUSIVE
(
	SYSTEM_EXCLUSIVE_ID		serial	NOT NULL,
	STOCK_INFOMATION_ID		int4	NOT NULL,
	SYS_USER_ID		int4	NOT NULL,
	DATA_DATE		timestamp	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_STOCK_EXCLUSIVE_pkey PRIMARY KEY (SYSTEM_EXCLUSIVE_ID, STOCK_INFOMATION_ID, SYS_USER_ID));


COMMENT ON TABLE T_STOCK_EXCLUSIVE IS '排他制御';
COMMENT ON COLUMN T_STOCK_EXCLUSIVE.SYSTEM_EXCLUSIVE_ID IS 'システムID';
COMMENT ON COLUMN T_STOCK_EXCLUSIVE.STOCK_INFOMATION_ID IS '在庫情報ID';
COMMENT ON COLUMN T_STOCK_EXCLUSIVE.SYS_USER_ID IS '操作ユーザー';
COMMENT ON COLUMN T_STOCK_EXCLUSIVE.DATA_DATE IS 'データ更新日時';
COMMENT ON COLUMN T_STOCK_EXCLUSIVE.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_STOCK_EXCLUSIVE.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_STOCK_EXCLUSIVE.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_STOCK_EXCLUSIVE.UPDATE_USER_ID IS '更新者ID';

