-- 在庫履歴

DROP TABLE T_STOCK_HISTORY;

CREATE TABLE T_STOCK_HISTORY
(
	STOCK_HISTORY_ID		serial	NOT NULL,
	CHANGE_DATE		timestamp,
	STAFF		text,
	STOCK_CHANGE		int4,
	STOCK_CHANGE_BEFORE		int4,
	STOCK_CHANGE_AFTER		int4,
	CHANGE_FLAG		char(1),
	REMARKS		text,
	ITEM_ID		char(4),
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_STOCK_HISTORY_pkey PRIMARY KEY (STOCK_HISTORY_ID));


COMMENT ON TABLE T_STOCK_HISTORY IS '在庫履歴';
COMMENT ON COLUMN T_STOCK_HISTORY.STOCK_HISTORY_ID IS '在庫履歴ID';
COMMENT ON COLUMN T_STOCK_HISTORY.CHANGE_DATE IS '変更日';
COMMENT ON COLUMN T_STOCK_HISTORY.STAFF IS '担当者';
COMMENT ON COLUMN T_STOCK_HISTORY.STOCK_CHANGE IS '変更数';
COMMENT ON COLUMN T_STOCK_HISTORY.STOCK_CHANGE_BEFORE IS '変更前';
COMMENT ON COLUMN T_STOCK_HISTORY.STOCK_CHANGE_AFTER IS '変更後';
COMMENT ON COLUMN T_STOCK_HISTORY.CHANGE_FLAG IS '増減フラグ';
COMMENT ON COLUMN T_STOCK_HISTORY.REMARKS IS '備考';
COMMENT ON COLUMN T_STOCK_HISTORY.ITEM_ID IS '商品ID';
COMMENT ON COLUMN T_STOCK_HISTORY.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN T_STOCK_HISTORY.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_STOCK_HISTORY.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_STOCK_HISTORY.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_STOCK_HISTORY.UPDATE_USER_ID IS '更新者ID';

