-- 在庫情報

DROP TABLE T_STOCK_INFOMATION;

CREATE TABLE T_STOCK_INFOMATION
(
	STOCK_INFOMATION_ID		serial	NOT NULL,
	STOCK_COUNT		int4,
	ASSUMPTION_STOCK_COUNT		int4,
	ITEM_ID		int4,
	DELETE_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_STOCK_INFOMATION_pkey PRIMARY KEY (STOCK_INFOMATION_ID));


COMMENT ON TABLE T_STOCK_INFOMATION IS '在庫情報';
COMMENT ON COLUMN T_STOCK_INFOMATION.STOCK_INFOMATION_ID IS '在庫情報ID';
COMMENT ON COLUMN T_STOCK_INFOMATION.STOCK_COUNT IS '在庫数';
COMMENT ON COLUMN T_STOCK_INFOMATION.ASSUMPTION_STOCK_COUNT IS '想定在庫数';
COMMENT ON COLUMN T_STOCK_INFOMATION.ITEM_ID IS '商品ID';
COMMENT ON COLUMN T_STOCK_INFOMATION.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN T_STOCK_INFOMATION.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_STOCK_INFOMATION.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_STOCK_INFOMATION.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_STOCK_INFOMATION.UPDATE_USER_ID IS '更新者ID';

