-- 在庫ロック

DROP TABLE T_STOCK_LOCK;

CREATE TABLE T_STOCK_LOCK
(
	SYSTEM_LOCK_ID		serial	NOT NULL,
	LOCK_FLAG		char(1)	DEFAULT '0'	NOT NULL,
	SYS_USER_ID		int4	NOT NULL,
	CREATE_DATE		timestamp	NOT NULL,
	CREATE_USER_ID		int4	NOT NULL,
	UPDATE_DATE		timestamp	NOT NULL,
	UPDATE_USER_ID		int4	NOT NULL,
CONSTRAINT T_STOCK_LOCK_pkey PRIMARY KEY (SYSTEM_LOCK_ID));


COMMENT ON TABLE T_STOCK_LOCK IS '在庫ロック';
COMMENT ON COLUMN T_STOCK_LOCK.SYSTEM_LOCK_ID IS 'システムID';
COMMENT ON COLUMN T_STOCK_LOCK.LOCK_FLAG IS '在庫情報ID';
COMMENT ON COLUMN T_STOCK_LOCK.SYS_USER_ID IS '操作ユーザー';
COMMENT ON COLUMN T_STOCK_LOCK.CREATE_DATE IS '登録日';
COMMENT ON COLUMN T_STOCK_LOCK.CREATE_USER_ID IS '登録者ID';
COMMENT ON COLUMN T_STOCK_LOCK.UPDATE_DATE IS '更新日';
COMMENT ON COLUMN T_STOCK_LOCK.UPDATE_USER_ID IS '更新者ID';

