-- 移行用旧伝票マスタ

DROP TABLE T_SLIP_MIGRATION;

CREATE TABLE T_SLIP_MIGRATION
(
	SYS_SLIP_ID		serial	NOT NULL,
	SLIP_MID		varchar(20),
	CUST_ID		varchar(20),
	SLIP_DATE		timestamp,
	OUTPPUT_FLAG		varchar(2),
	ORDERS_ROUTE		varchar(2),
	HASSOU		varchar(2),
	KUBUN		varchar(2),
	SLIP_PRINT		varchar(2),
	PCID		varchar(10),
	PAYMENT		int4,
	PAYMENT_DATE		timestamp,
	REMARKS		text,
	OFFICE		char(1),
CONSTRAINT T_SLIP_MIGRATION_pkey PRIMARY KEY (SYS_SLIP_ID));


COMMENT ON TABLE T_SLIP_MIGRATION IS '移行用旧伝票マスタ';
COMMENT ON COLUMN T_SLIP_MIGRATION.SYS_SLIP_ID IS 'システム旧伝票ID';
COMMENT ON COLUMN T_SLIP_MIGRATION.SLIP_MID IS '伝票MID';
COMMENT ON COLUMN T_SLIP_MIGRATION.CUST_ID IS '顧客ID';
COMMENT ON COLUMN T_SLIP_MIGRATION.SLIP_DATE IS '伝票作成日';
COMMENT ON COLUMN T_SLIP_MIGRATION.OUTPPUT_FLAG IS '出力データ作成フラグ';
COMMENT ON COLUMN T_SLIP_MIGRATION.ORDERS_ROUTE IS '担当ID';
COMMENT ON COLUMN T_SLIP_MIGRATION.HASSOU IS '発送ID';
COMMENT ON COLUMN T_SLIP_MIGRATION.KUBUN IS '区分ＩＤ';
COMMENT ON COLUMN T_SLIP_MIGRATION.SLIP_PRINT IS '払込伝票印刷';
COMMENT ON COLUMN T_SLIP_MIGRATION.PCID IS 'PCID';
COMMENT ON COLUMN T_SLIP_MIGRATION.PAYMENT IS '入金';
COMMENT ON COLUMN T_SLIP_MIGRATION.PAYMENT_DATE IS '入金日';
COMMENT ON COLUMN T_SLIP_MIGRATION.REMARKS IS '備考';
COMMENT ON COLUMN T_SLIP_MIGRATION.OFFICE IS '営業所';

