-- 移行用旧明細

DROP TABLE T_SLIP_ITEM_MIGRATION;

CREATE TABLE T_SLIP_ITEM_MIGRATION
(
	SYS_SLIP_ITEM_ID		serial	NOT NULL,
	SLIP_ITEM_ID		varchar(20),
	ITEM_ID		varchar(64),
	UNIT_PRICE		numeric,
	ITEM_QUANTITY		int4,
	AMOUNT		int4,
	SALES_TAX		int4,
	CUST_ID		varchar(20),
	SLIP_MID		varchar(20),
	MEISAI_FLAG		char(1),
	ITEM_FLAG		char(1),
	REMARKS		text,
	OFFICE		char(1),
CONSTRAINT T_SLIP_ITEM_MIGRATION_pkey PRIMARY KEY (SYS_SLIP_ITEM_ID));


COMMENT ON TABLE T_SLIP_ITEM_MIGRATION IS '移行用旧明細';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.SYS_SLIP_ITEM_ID IS 'システム旧明細ID';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.SLIP_ITEM_ID IS '明細ID';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.ITEM_ID IS '商品ID';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.UNIT_PRICE IS '単価2';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.ITEM_QUANTITY IS '数量';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.AMOUNT IS '金額２';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.SALES_TAX IS '消費税２';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.CUST_ID IS '顧客ID';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.SLIP_MID IS '伝票MID';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.MEISAI_FLAG IS '明細区分';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.ITEM_FLAG IS '商品区分';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.REMARKS IS '備考';
COMMENT ON COLUMN T_SLIP_ITEM_MIGRATION.OFFICE IS '営業所';

